services:
  asktable:
    # AskTable
    #image: registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:latest  # 中国大陆地区
    image: datamini/asktable-all-in-one:latest   # 其他地区
    container_name: asktable
    depends_on:
      - asktable_mysql
    ports:
      - 8000:80
    environment:
      TZ: Asia/Shanghai
      BASE_URL: ${BASE_URL}        # 【须修改】容器对外暴露的地址（即从外部比如浏览器访问的地址）
      LLM_API_KEY: ${LLM_API_KEY}           # 【须修改】AI 模型令牌，是以“asktable-”开头的字符串。登录 AskTable(https://cloud.asktable.com/?dialog=deployment) 获取。
      MYSQL_HOST: asktable_mysql               # MySQL 数据库地址（该 MySQL 是 AskTable 数据库，并不是希望利用 AskTable 去查询的数据库，后者需要在 Web 页面上添加）
      MYSQL_USER: asktable                     # MySQL 数据库用户名
      MYSQL_PASSWORD: asktable                 # MySQL 数据库密码
      MYSQL_DB: asktable                       # MySQL 数据库名称
    volumes:
      - ./asktable_data:/asktable

  asktable_mysql:
    #image: registry.cn-shanghai.aliyuncs.com/dminfra/mysql:8.0.27  # 中国大陆地区
    image: mysql:8.0.27   # 其他地区
    container_name: asktable_mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: asktable
      MYSQL_DATABASE: asktable
      MYSQL_USER: asktable
      MYSQL_PASSWORD: asktable
    volumes:
      - ./mysql_data:/var/lib/mysql