RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-asktable
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: AI 模型令牌
  ConstraintDescription: ''
  Default: ''
  Name: LLM_API_KEY
DockerComposeYamlPath: docker-compose.yml
Owner: workhardliuzheng
Branch: liuzheng
Platform: github
